### ISSUE TITLE
 Issue with PSPython SDK Installation

### ISSUE THREAD

**Issue by pavijovi3** [PalmSens/MethodSCRIPT_Examples#2]
I am experiencing an issue while attempting to install the PSPython SDK for my EmStat3 Blue potentiostat. I am trying to code the PSPython SDK to control the EmStat3 potentiostat, generate a square wave when triggered by an external TTL signal from the spectrometer. 

I have encountered difficulties during the installation process, and I would greatly appreciate your help.

Issue Description: I have downloaded the PSPython SDK folder from the website, and I am attempting to install it as a Python package so that I can control my EmStat3 Blue potentiostat using Python scripts. However, I have encountered the following problem:

When I attempt to install the SDK using the pip install . command in the SDK folder directory, I receive the error message: "ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found."

PSPython SDK Folder: C:\Users\r01pg22\Downloads\PSPythonSDK and  R:\COPS\sncs\Electrochemistry\Pavi\PSPythonSDK\pspython both got me same error.
Python Environment: Python 3.8 - PyCharm
Operating System: Windows 10
Steps Taken: I have tried various approaches to install the SDK locally, but none have been successful. I attempted to mention the directory (pspython_folder = r"R:\COPS\sncs\Electrochemistry\Pavi\PSPythonSDK\pspython") in the code but the issue persists. I could not find proper documentation on how to install this and read me.txt file had limited information. please also add some example code without using methodscript.

Thank you.

**Comment by ThierryPalmSens** [comment]
Thank you for bringing this to our attention. I understand the confusion, the limited documentation for the PSPython SDK is not very clear on this. The PSPython is not a module that is available in pip, it is a local module. To use the pspython module in a python script please make sure to:
1. Copy to the pspython folder to the folder in which your python script is located.
2. Run `pip -r requirements.txt` to install the necessary dependencies.

Then the module can be used as demonstrated in the included example scripts.

For further questions please contact me or our support at thierry@palmsens.com or support@palmsens.com.

**Comment by pavijovi3** [comment]
Thank you for the prompt response. I have placed my Python script in the recommended folder and have installed the required dependencies as specified in the requirements.txt file. 

I am trying to find detailed documentation for the Python version of the PalmSens SDK, specifically for the classes and methods available for controlling the EmStat3 Blue potentiostat. In my script, I encountered an issue where I couldn't find a reference to the 'SquareWave' class in 'pspymethods.py.' I have found the "Getting started with PalmSens SDK for WinForms" documentation, but I am uncertain if this documentation is applicable to Python. Could you please provide me with Python-specific documentation or guidance on how to use the 'SquareWave' method in Python? Attached a copy of my script for reference. 
[pulse-stepscan - Copy.txt](https://github.com/PalmSens/MethodSCRIPT_Examples/files/12618412/pulse-stepscan.-.Copy.txt)

**Comment by ThierryPalmSens** [comment]
Unfortunately, there is no documentation for the PSPython SDK yet, it is still in pre-release, although, our website does not mention this. Appendix A of the `Getting Started with PalmSens SDK for WinForms` would be the most useful in your case.

![image](https://github.com/PalmSens/MethodSCRIPT_Examples/assets/38280420/c6aa573f-6328-41ae-b632-a908df5b0568)

Some references are actually references to our c# libraries, the pythonnet libraries can import these, and the namespaces and properties for the techniques can be found in our WinForms documentation. My initial intention was to create a wrapper in python for all techniques, but further work on this project has been postponed. 

![image](https://github.com/PalmSens/MethodSCRIPT_Examples/assets/38280420/b54fb123-c308-4baa-a262-a1e5ad84249d)

To import classes from our c# SDK libraries you can use the standard import function and provide the corresponding namespace in c#, for example `from PalmSens.Techniques import SquareWave`.. Using the debug console it is possible to inspect a class and view all of its methods and properties.

Here is a link to a more up-to-date version of the PSPython SDK, I have included a SWVExample.py example for you.

https://drive.google.com/file/d/1diIhNiQDoy4jSnslKMbSFR3kO8PF3Nf2/view?usp=sharing

**Comment by pavijovi3** [comment]
Hi,

Thank you so much for the quick response again. I think i have done something similar to include square wave but I will try your updated SDK. I am trying to use the spectrometer as a master to send a 5V trigger, so the emstat3 blue can send a square wave pulse. I connected the trigger to pin 4 Rx (TTL comm) but when I do this, the potentiostat is not connecting with the script. I tried pin 2 (d3 digital input/output (5V)) but it seems to send a 5V back to the spectrometer trigger overloading it. not sure which would be the best pin to connect here.

```python
import sys
from pspython.pspyinstruments import InstrumentManager
from pspython.pspymethods import square_wave_voltammetry

# Add the directory containing the pspython package to the Python path
pspython_dir = r'C:\Users\r01pg22\Downloads\PSPythonSDK\pspython'
sys.path.append(pspython_dir)


# Define a callback function for receiving new data
def new_data_callback(new_data):
    for key, value in new_data.items():
        print(key + ' = ' + str(value))


# Initialize the instrument manager with the callback function
manager = InstrumentManager(new_data_callback=new_data_callback)

# Discover available instruments
available_instruments = manager.discover_instruments()

if not available_instruments:
    print("No instruments found. Please make sure the EmStat3 Blue is connected.")
else:
    # Assuming the first available instrument is the EmStat3 Blue
    selected_instrument = available_instruments[0]

    # Connect to the EmStat3 Blue
    success = manager.connect(selected_instrument)

    if success != 1:
        print("Failed to connect to the EmStat3 Blue.")
    else:
        print("Connected to the EmStat3 Blue.")

        # Prompt user for measurement parameters
        start_potential = float(input("Enter start potential (V): "))
        end_potential = float(input("Enter end potential (V): "))
        pulse_potential = float(input("Enter pulse potential (V): "))
        pulse_duration = float(input("Enter pulse duration (s): "))

        # Configure trigger settings
        trigger_enabled = input("Enable trigger (y/n): ").lower() == 'y'

        if trigger_enabled:
            trigger_voltage_high = float(input("Enter trigger voltage when high (V): "))

        # Create a SquareWave method
        square_wave_method = square_wave_voltammetry(
            begin_potential=start_potential,
            end_potential=end_potential,
            step_potential=0.0,  # Set step potential to 0 for square wave
            pulse_amplitude=pulse_potential,
            frequency=0.0,  # Frequency set to 0 for external trigger mode
        )

        # Set trigger settings
        square_wave_method.TriggerEnabled = trigger_enabled

        if trigger_enabled:
            square_wave_method.TriggerVoltageHigh = trigger_voltage_high

        # Perform the square wave measurement
        measurement = manager.measure(square_wave_method)

        if measurement is not None:
            print("Square wave measurement started.")
        else:
            print("Failed to start the measurement.")

        # Disconnect from the instrument after the measurement
        success = manager.disconnect()

        if success == 1:
            print("Disconnected from the EmStat3 Blue.")
        else:
            print("Error while disconnecting.")

# End of the program
```

```none
C:\Users\r01pg22\Downloads\PSPythonSDK\venv\Scripts\python.exe "C:\Users\r01pg22\Downloads\PSPythonSDK\pulse-stepscan - Copy.py" 
Connected to the EmStat3 Blue.
Enter start potential (V): 0.05
Enter end potential (V): 0.05
Enter pulse potential (V): 0.35
Enter pulse duration (s): 10
Enable trigger (y/n): y
Enter trigger voltage when high (V): 5
Failed to start the measurement.
Traceback (most recent call last):
  File "C:\Users\r01pg22\Downloads\PSPythonSDK\pspython\pspyinstruments.py", line 101, in measure
    self.__comm.Measure(method)
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Double value)
   at PalmSens.EncodedMethodV1(String , Single )
   at PalmSens.Techniques.CyclicVoltammetry.ToHex1(EncodedMethodV1 m)
   at PalmSens.Method.ToHex(Int32 rev, DeviceCapabilities capabilities)
   at PalmSens.Comm.CommMeasurement.StartMeasurement(Boolean init, Boolean OCPDetermined)
   at PalmSens.Comm.CommMeasurement.Start()
   at PalmSens.Comm.CommManager.(Method , Int32 , MeasType )
   at PalmSens.Comm.CommManager.Measure(Method m, Int32 muxchannel)
Disconnected from the EmStat3 Blue.

Process finished with exit code 0
```

**Comment by ThierryPalmSens** [comment]
Waiting for a digital trigger is possible but that requires some extra work, I would recommend adding something like this to the `pspyinstruments.py` in the pspython folder.

```
    async def wait_digital_trigger(self, wait_for_high):
        if self.__comm is None:
            print('Not connected to an instrument')
            return 0   

        try: 
            # obtain lock on library (required when communicating with instrument)
            self.__comm.ClientConnection.Semaphore.Wait()

            while True:
                if self.__comm.DigitalLineD0 == wait_for_high:
                    break
                await asyncio.sleep(.05)

            self.__comm.ClientConnection.Semaphore.Release()

        except Exception as e:
            traceback.print_exc()        

            if self.__comm.ClientConnection.Semaphore.CurrentCount == 0:
                # release lock on library (required when communicating with instrument)
                self.__comm.ClientConnection.Semaphore.Release()

        return
```

A new link with an updated example: https://drive.google.com/file/d/1diIhNiQDoy4jSnslKMbSFR3kO8PF3Nf2/view?usp=sharing

**Comment by ThierryPalmSens** [comment]
Please note that this example waits for Pin 2 (d3) to be pulled down to 0, I am not aware if it can be reconfigured to be pulled up.

![image](https://github.com/PalmSens/MethodSCRIPT_Examples/assets/38280420/ac7de727-e7cf-4b57-a1c4-0e36d17eca2d)

**Comment by pavijovi3** [comment]
Hi Thierry,

Thanks for helping me with this. The spectrometer send a 5V trigger signal and If Pin 2 (d3) waits to be pulled down, Then, I am not sure if it can be used as trigger. is there anything else you can suggest I do? Any other way to use the 5V signal as a trigger for the emstat3 blue?

**Comment by ThierryPalmSens** [comment]
@HielkeVeringa can you think of a solution that would allow the spectrometer to trigger the EmStat Blue?

**Comment by pavijovi3** [comment]
Hi Thierry,

I was also thinking is there a way to configure the Pin 2 to be an digital input or maybe use the pin 3 with a voltage divider to drop the 5V signal from the spectrometer to 3.5V and use that as the trigger. In that case how can I code that trigger into my python program or is there a way to use method script? 
Open for any advice.

Thank you.

**Comment by ThierryPalmSens** [comment]
Sorry for the confusion, it should work without any changes other than using true as the argument:

`await manager.wait_digital_trigger(True)`

**Comment by pavijovi3** [comment]
Hi Thierry,

thank for updating me. the code seems to work with Pin 2 but if I change the step potential from 0.05 to 0.35V, it prints disconnected. Not sure what is the problem. After the pulse wave comes back to 0.05V, I would like the cell to stay ON and maintain the 0.05V until the next trigger and continue sending step wave until I stop the code.

```python
import pspython.pspyinstruments as pspyinstruments
import asyncio

from PalmSens import CurrentRange
from PalmSens import CurrentRanges
from PalmSens import Method


def current_range(id):
    """
    100 pA = 0,
    1 nA = 1,
    10 nA = 2,
    100 nA = 3,
    1 uA = 4,
    10 uA = 5,
    100 uA = 6,
    1 mA = 7,
    10 mA = 8,
    100 mA = 9,
    2 uA = 10,
    4 uA = 11,
    8 uA = 12,
    16 uA = 13,
    32 uA = 14,
    63 uA = 26,
    125 uA = 17,
    250 uA = 18,
    500 uA = 19,
    5 mA = 20,
    6 uA = 21,
    13 uA = 22,
    25 uA = 23,
    50 uA = 24,
    200 uA = 25
    """
    return CurrentRange(CurrentRanges(id))


def new_data_callback():
    def print_results(new_data):
        for type, value in new_data.items():
            print(type + ' = ' + str(value))

    return lambda x: print_results(x)


from PalmSens.Techniques import SquareWave


async def main():
    method = SquareWave()
    method.Ranging.MaximumCurrentRange = current_range(8)
    method.Ranging.MinimumCurrentRange = current_range(4)
    method.Ranging.StartCurrentRange = current_range(6)
    method.ConditioningTime = 0  # Time (s)
    method.ConditioningPotential = 0  # potential (V)
    method.DepositionTime = 0  # Time (s)
    method.DepositionPotential = 0  # potential (V)
    method.EquilibrationTime = 0  # Time (s)
    method.BeginPotential = -0.05  # potential (V)
    method.EndPotential = 0.05  # potential (V)
    method.StepPotential = 0.35  # potential (V)
    method.PulseAmplitude = 0.1  # potential (V)
    method.Frequency = 5  # frequency (Hz)

    available_instruments = pspyinstruments.discover_instruments()

    if (len(available_instruments) < 1):
        return

    manager = (pspyinstruments.InstrumentManager(new_data_callback=new_data_callback()))
    connected = manager.connect(available_instruments[0])

    if connected:
        await manager.wait_digital_trigger(True)

        # start measurement asynchronously
        measurement = await manager.measure_async(method)

        success = manager.disconnect()
        if success:
            print('disconnected')
        else:
            print('error while disconnecting')


asyncio.run(main())
```

Please advice.

**Comment by pavijovi3** [comment]
Hi thierry,

I think there is some limitation between begin potential, end potential and step potential. I have attached a picture saying how the pulse should behave for my step-scan measurements with the spectrometer. Maybe Pulse Amperometric detection is better? 
Could you advise me to resolve this?
![step-scan](https://github.com/PalmSens/MethodSCRIPT_Examples/assets/13885804/6e4fa0a6-d4f1-47b0-9721-305e6498413b)

**Comment by ThierryPalmSens** [comment]
The Python SDK does not validate the method for you, the maximum StepPotential for an EmStat3 Blue is 0.25V. I recommend using PSTrace to check whether your method parameters are valid. I am also afraid that the EmStat3 Blue cannot trigger at the start of a pulse during measurements. You will need an instrument that supports MethodSCRIPT, EmStat Pico / Sensit / EmStat4 series instruments.
